stages:
  preprocess:
    cmd: PYTHONPATH=. python -m src.data_preprocessing.preprocess_spark --params
      conf/preprocess.yaml
    deps:
    - conf/preprocess.yaml
    - data/raw
    - src/data_preprocessing/preprocess_spark.py
    outs:
    - data/processed
  train:
    cmd: PYTHONPATH=. MLFLOW_TRACKING_URI=http://127.0.0.1:5001 python -m 
      src.training.train_spark_mllib --params conf/train.yaml
    deps:
    - conf/train.yaml
    - data/processed
    - src/training/train_spark_mllib.py
    outs:
    - reports/training
  register_model:
    cmd: MLFLOW_TRACKING_URI=http://127.0.0.1:5001 PYTHONPATH=. python -m 
      src.registry.promote_to_production
    deps:
    - reports/training/run_id.txt
    - src/registry/promote_to_production.py
    outs:
    - reports/registry
